// Cypress Test: capture
// Description: teste
// Generated by CypressGen Pro

/// <reference types="cypress" />

describe('capture', () => {
  it('teste', () => {
    // Navigate to URL
    cy.visit('https://qa.sgpm.inovvati.com.br/#/auth/login');

    // Click element
    cy.get('.colored-div').should('be.visible').click();

    // Click element
    cy.get('span').should('be.visible').click();

    // Click element
    cy.get('span').should('be.visible').click();

    // Click element
    cy.get('[data-cy="login_id"]').should('be.visible').click();

    // Type into input field
    cy.get('[data-cy="login_id"]').should('be.visible').clear().type('d');

    // Type into input field
    cy.get('[data-cy="login_id"]').should('be.visible').clear().type('dev');

    // Click element
    cy.get('[data-cy="password_id"]').should('be.visible').click();

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('P');

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('P2');

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('P2sg');

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('P2sg1');

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('P2sg142');

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('P2sg14253');

    // Click element
    cy.get('[data-cy="submit_id"]').should('be.visible').click(); // ACESSAR

    // Click element
    cy.get('[role="img"]').should('be.visible').click(); // close

    // Click element
    cy.get('[data-cy="login_id"]').should('be.visible').click();

    // Type into input field
    cy.get('[data-cy="login_id"]').should('be.visible').clear().type('desv');

    // Type into input field
    cy.get('[data-cy="login_id"]').should('be.visible').clear().type('desev');

    // Click element
    cy.get('.block').should('be.visible').click(); // ACESSAR

    // Click element
    cy.get('.colored-div').should('be.visible').click();

    // Click element
    cy.get('[data-cy="login_id"]').should('be.visible').click();

    // Type into input field
    cy.get('[data-cy="login_id"]').should('be.visible').clear().type('desev');

    // Type into input field
    cy.get('[data-cy="login_id"]').should('be.visible').clear().type('dev');

    // Click element
    cy.get('.q-btn__content').should('be.visible').click(); // ACESSAR

    // Click element
    cy.get('[role="presentation"]').should('be.visible').click(); // visibility

    // Click element
    cy.get('[data-cy="password_id"]').should('be.visible').click();

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('Psg142536');

    // Type into input field
    cy.get('[data-cy="password_id"]').should('be.visible').clear().type('P@sg142536');

    // Navigate to URL
    cy.visit('https://qa.sgpm.inovvati.com.br/#/config/programa-financiamento-selecionar');

    // Navigate to URL
    cy.visit('https://qa.sgpm.inovvati.com.br/#/');

    // Click element
    cy.get('[role="button"]').should('be.visible').click(); // IR

    // Click element
    cy.get('.q-item__section').should('be.visible').click(); // Orçamento

    // Navigate to URL
    cy.visit('https://qa.sgpm.inovvati.com.br/#/orcamento-vigente-listar');

    // Click element
    cy.get('span').should('be.visible').click(); // Vigente

    // Navigate to URL
    cy.visit('https://qa.sgpm.inovvati.com.br/#/orcamento-vigente-novo');

    // Click element
    cy.get('.block').should('be.visible').click(); // NOVO

  });
});
